### ISSUE TITLE
And this behavior is bad because...

### ISSUE THREAD

**Issue by baverman** [benjamingr/favicon-bug#3]
???

Did you think about that any static resource can be huge? And this is a problem of site owner but not an enduser. There will be enormous num of bugs (especially with a buf overflow) if browser devs decide to detect invalid (pfff) content. Are you work for NSA?

**Comment by benjamingr** [comment]
🎈🎈🎈

**Comment by benjamingr** [comment]
(All of these are answered in the HN thread here if you really care and not just trolling: https://news.ycombinator.com/item?id=9720665)
